### PR TITLE
Update Crypto.php (Minor: Spelling)

### PR DESCRIPTION
**Pull request by tittlejonathan**
Just a few spelling corrections; noticed them when I was testing Halite on a current project.

### CODE REVIEW

**Comment by paragonie-scott** [comment]
Thanks, not sure how I overlooked those. :+1:

**Comment by tittlejonathan** [comment]
No problem :+1: - now if the libsodium PHP extension will work, I'll be able to actually implement (not an issue with Halite).

**Comment by paragonie-scott** [comment]
The instructions [here](https://github.com/paragonie/pecl-libsodium-doc/blob/master/chapters/00-intro.md#installing-libsodium-and-the-php-extension) should work. Let me know if you get stuck. :)

**Comment by tittlejonathan** [comment]
@paragonie-scott - Reopening for a quick question. Would you prefer I direct questions to the project (Halite) or through the contact form (since it's not directly related to Halite - essentially I'm getting an error stating that all \Sodium\* classes/methods do not exist)?

**Comment by paragonie-scott** [comment]
Feel free to post them here. The contact form goes to several people.

**Pull request merged**
