### PR TITLE
Remove access modifier final from private methods (PHP 8 support)

### PR DESCRIPTION
**Pull request by junaidbinfarooq**
Removes access modifier `final` from private methods as such methods are never overridden by other classes.

### CODE REVIEW

**Comment by spaze** [comment]
Just a heads up that this solves a new PHP 8.0 warning:

> Warning: Private methods cannot be final as they are never overridden by other classes

See https://3v4l.org/rl4ti

**Comment by junaidbinfarooq** [comment]
> Just a heads up that this solves a new PHP 8.0 warning:
> 
> > Warning: Private methods cannot be final as they are never overridden by other classes
> 
> See https://3v4l.org/rl4ti

Well, that is what I exactly tried to fix. :)

**Comment by spaze** [comment]
> Well, that is what I exactly tried to fix. :)

Just adding a context so the maintainer can prioritize properly.

**Comment by spaze** [comment]
Hey @paragonie-security, can you please merge this and prepare a new release to support PHP 8.0? Thank you! :-)

**Comment by junaidbinfarooq** [comment]
Anyone merging this PR? @paragonie-security?

**Comment by spaze** [comment]
@paragonie-scott @paragonie-staff Any chance of merging this soon for flawless PHP 8 support? Thanks!

**Pull request merged**
