### PR TITLE
Updated the namespace config class to Baseconfig #44

### PR DESCRIPTION
**Pull request by usmanzafar**
Updated the namespace config class to Baseconfig (this name is used in Symmetric/Config as well) Fixes https://github.com/paragonie/halite/issues/44

### CODE REVIEW

**Comment by sstok** [comment]
👍 @paragonie-scott this is safe to merge and should fix the failures with the Symfony Debug component.

There is also #46 but it changes the expected class, which could a BC break.

**Comment by usmanzafar** [comment]
yea I did look at that before I submitted this. Cheers fella! keen to have this sorted  and be available in a new tag if applicable. Thanks for looking into this.

**Comment by frederikbosch** [comment]
I would also love to see this merged.

**Comment by frederikbosch** [comment]
@paragonie-scott Thanks!

**Pull request merged**
