### PR TITLE
Fixed failing travis build (libsodium v1.0.8)

### PR DESCRIPTION
**Pull request by AndrewCarterUK**
Not sure 1.0.9 has been tagged yet: https://github.com/jedisct1/libsodium/releases

### CODE REVIEW

**Comment by AndrewCarterUK** [comment]
Apparently not fixed, travis error:

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested PHP extension ext-libsodium ^1.0.3 has the wrong version (1.0.2) installed. Install or enable PHP's libsodium extension.
```

**Comment by AndrewCarterUK** [comment]
Looks like 1.0.3 hasn't been tagged yet for ext-libsodium either: https://github.com/jedisct1/libsodium-php/releases

**Comment by AndrewCarterUK** [comment]
oof.

```
1) KeyPairTest::testDeriveSigningKey
Error: Undefined constant 'Sodium\CRYPTO_PWHASH_SALTBYTES'
/home/travis/build/paragonie/halite/src/KeyFactory.php:266
/home/travis/build/paragonie/halite/test/unit/KeyPairTest.php:48
2) KeyTest::testDerive
Error: Undefined constant 'Sodium\CRYPTO_PWHASH_SALTBYTES'
/home/travis/build/paragonie/halite/src/KeyFactory.php:166
/home/travis/build/paragonie/halite/test/unit/KeyTest.php:22
3) KeyTest::testDeriveSigningKey
Error: Undefined constant 'Sodium\CRYPTO_PWHASH_SALTBYTES'
/home/travis/build/paragonie/halite/src/KeyFactory.php:266
/home/travis/build/paragonie/halite/test/unit/KeyTest.php:77
4) KeyTest::testEncKeyStorage
Error: Undefined constant 'Sodium\CRYPTO_PWHASH_SALTBYTES'
/home/travis/build/paragonie/halite/src/KeyFactory.php:212
/home/travis/build/paragonie/halite/test/unit/KeyTest.php:184
5) KeyTest::testSignKeyStorage
Error: Undefined constant 'Sodium\CRYPTO_PWHASH_SALTBYTES'
/home/travis/build/paragonie/halite/src/KeyFactory.php:266
/home/travis/build/paragonie/halite/test/unit/KeyTest.php:248
6) PasswordTest::testEncrypt
Error: Call to undefined function Sodium\crypto_pwhash_str()
/home/travis/build/paragonie/halite/src/Password.php:27
/home/travis/build/paragonie/halite/test/unit/PasswordTest.php:15
--
There was 1 failure:
1) HaliteTest::testLibsodiumDetection
Failed asserting that false is true.
/home/travis/build/paragonie/halite/test/unit/HaliteTest.php:13
```

**Comment by jedisct1** [comment]
It's not, because the final version will not use Argon2i. Do not use `crypto_pwhash()` now.

**Comment by paragonie-scott** [comment]
@AndrewCarterUK Version 2 isn't released yet. Check [the stable branch](https://github.com/paragonie/halite/tree/stable). :)

> It's not, because the final version will not use Argon2i.

Does this mean they're going to release a mitigation? Or that you're considering e.g. Argon2id instead?

> Do not use `crypto_pwhash()` now.

Good advice.

**Pull request closed without merging**
