### PR TITLE
Added support for phpunit v6.3

### PR DESCRIPTION
**Pull request by prisis**

### CODE REVIEW

**Comment by prisis** [comment]
@paragonie-scott should it be libsodium ^1.0.6 or can i update it to v2

**Comment by lunika** [comment]
halite is not compatible with libsodium v2 AFAIK. The `Sodium` namespace does not exists anymore, everything is in the main namespace (`\Sodium\bin2hex` is now `sodium_bin2hex`)

**Comment by prisis** [comment]
i'm gonna fix this today!

**Comment by prisis** [comment]
@paragonie-scott this pr is ready

**Pull request merged**
